# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('controlUrl', models.URLField(default=None)),
                ('shortUrl', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('noOfVisitors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short.Url')),
            ],
        ),
    ]
